version: '3.8'
services:
      BOT:
            image: postgres:15.1-alpine
            container_name: BOT_TEST
            environment:
                  - POSTGRES_USER=${DB_USER}
                  - POSTGRES_PASSWORD=${DB_PASSWORD}
                  - POSTGRES_DB=${DB_NAME}
            volumes:
                  - postgres_data:/var/lib/postgresql/data
            ports:
                  - '2465:5432'
volumes:
  postgres_data: